name: build

on:
  workflow_dispatch:
    inputs:
      test_build:
        description: 'Test build'
        required: false
        default: 'false'
        type: choice
        options:
        - true
        - false
      fake_build:
        description: 'Fake build'
        required: false
        default: 'false'
        type: choice
        options:
        - true
        - false
      max_speed:
        description: 'Build with max speed'
        required: false
        default: 'true'
        type: choice
        options:
        - true
        - false
  push:
    tags:
      - v[0-9]+*

env:
  TEST_BUILD: ${{ github.event.inputs.test_build == 'true' }}
  FAKE_BUILD: ${{ github.event.inputs.fake_build == 'true' }}
  MAX_SPEED: ${{ github.event.inputs.max_speed != 'false' }}
  TAG_SUFFIX: ${{ github.event.inputs.fake_build == 'true' && '-fake' || github.event.inputs.test_build == 'true' && '-test' || '' }}
  REPO_URL: https://github.com/TanLan112/zapret-openwrt
  REPO_LNK: TanLan112/zapret-openwrt
  REPO_BRANCH: master
  BUILD_ROOT: ${{ github.workspace }}/builder
  BUILD_DATE: unknown
  REPO_DATE: unknown
  LUCI_ARCH: aarch64_cortex-a53

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.gh.outputs.tag }}
      date: ${{ steps.gh.outputs.date }}
      sha: ${{ steps.gh.outputs.sha }}
      url: ${{ steps.gh.outputs.url }}
      message: ${{ steps.gh.outputs.message }}
      build_date: ${{ steps.gh.outputs.build_date }}
      fw_date: ${{ steps.gh.outputs.fw_date }}
      is_active: ${{ steps.activity.outputs.is_active }}
      test_build: ${{ env.TEST_BUILD }}
      fake_build: ${{ env.FAKE_BUILD }}
    steps:
      - name: Get repo data via GH API
        id: gh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          BRANCH=$(gh api repos/$REPO_LNK --jq '.default_branch')
          REPO_DATE=$(gh api repos/$REPO_LNK/commits/$BRANCH --jq '.commit.committer.date')
          BUILD_DATE=$( date --utc +'%Y%m%d' )
          FW_DATE=$( date --utc +'%Y-%m-%d' )
          {
            echo "tag=$GITHUB_REF_NAME"
            echo "date=$(date --utc -d $REPO_DATE +%Y%m%d)"
            echo "sha=$(gh api repos/$REPO_LNK/commits/$BRANCH --jq '.sha[0:7]')"
            echo "url=$(gh api repos/$REPO_LNK/commits/$BRANCH --jq '.html_url')"
            echo "message<<EOF"
            gh api repos/$REPO_LNK/commits/$BRANCH --jq '.commit.message'
            echo EOF
            echo "build_date=$BUILD_DATE"
            echo "fw_date=$FW_DATE"
          } >> $GITHUB_OUTPUT
          echo "REPO_DATE=$REPO_DATE" >> $GITHUB_ENV

      - name: Check for repo activity
        id: activity
        env:
          REPO_DATE: ${{ env.REPO_DATE }}
          URL: ${{ steps.gh.outputs.url }}
        run: |
          TIMESTAMP=$(date --utc -d $REPO_DATE +%s)
          DAYS=$(( ( $(date --utc +%s) - $TIMESTAMP ) / 86400 ))
          if [ "${{ github.event_name }}" != "schedule" ]; then
            is_active=true
          elif [[ $DAYS -lt 1 ]] ; then
            is_active=true
          else
            is_active=false
          fi
          echo "is_active=$is_active" >> $GITHUB_OUTPUT

  build:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: [ openwrt-24.10, SNAPSHOT ]
        arch:
          - aarch64_cortex-a53
          - x86_64
        isTestOrFake:
          - ${{ needs.check.outputs.test_build == 'true' || needs.check.outputs.fake_build == 'true' }}
    container:
      image: openwrt/sdk:${{ matrix.arch }}-${{ matrix.branch }}
      options: --user root
    outputs:
      pkgver: ${{ steps.build.outputs.pkgver }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO_LNK }}
          path: zapret-openwrt

      - name: Setup OpenWrt SDK
        working-directory: /builder
        shell: bash
        run: |
          ./setup.sh
          if [ "$BRANCH" = "openwrt-24.10" ]; then
              echo "PKGTYPE=ipk" >> $GITHUB_ENV
          else
              echo "PKGTYPE=apk" >> $GITHUB_ENV
          fi

      - name: Init packages
        id: init
        working-directory: '/builder'
        shell: bash
        run: |
          PKGDIR=$GITHUB_WORKSPACE/zapret-openwrt
          MKFN=$PKGDIR/luci-app-zapret/Makefile
          PKGVER=$( grep -s '^PKG_VERSION:=.*' $MKFN | cut -d'=' -f2 )
          cp -vr $PKGDIR ./package/zapret-openwrt/
          ./scripts/feeds update base packages luci
          ./scripts/feeds install -a
          echo "PKGVER=$PKGVER" >> $GITHUB_ENV
          echo "pkgver=$PKGVER" >> $GITHUB_OUTPUT
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Build packages        
        id: build
        if: steps.init.outputs.status == 'success'
        working-directory: '/builder'
        shell: bash
        run: |
          MAKE_JOBS=$(($(nproc)+1))
          PKGLIST=`echo package/zapret-openwrt/{zapret,zapret-tpws,zapret-mdig,luci-app-zapret}/compile`
          make -j$MAKE_JOBS $PKGLIST CONFIG_CCACHE=1
          OUTDIR=$GITHUB_WORKSPACE/$PKGTYPE-$ARCH
          mkdir -p $OUTDIR
          cp -R ./bin/packages/*/base/. $OUTDIR/
          echo "OUTDIR=$OUTDIR" >> $GITHUB_ENV
          echo "pkgver=$PKGVER" >> $GITHUB_OUTPUT
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Compress build logs
        if: always()
        run: |
          tar -cJvf logs-$BRANCH-$ARCH.tar.xz ./logs

      - name: Upload packages
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@main
        with:
          path: ${{ env.OUTDIR }}
          name: zapret,${{ env.PKGTYPE }},${{ matrix.arch }}
          if-no-files-found: error

  release:
    needs: [ check, build ]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: zapret,*

      - name: Put packages into zip
        run: |
          mkdir -p public
          cp -R zapret,ipk,*/*.ipk public/
          zip -j public/zapret_v${{ needs.build.outputs.pkgver }}.zip public/*

      - name: Upload to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag: v${{ needs.build.outputs.pkgver }}${{ env.TAG_SUFFIX }}
          name: zapret v${{ needs.build.outputs.pkgver }}
          body: "zapret v${{ needs.build.outputs.pkgver }} for OpenWrt"
          files: ./public/*.zip
